import type { AppIntentHostConfig, AppShortcutConfig } from '../../config';

function escapeSwiftString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/** App Shortcut phrases keep `\(.applicationName)` for the Shortcuts DSL. */
function escapeAppShortcutPhrase(s: string): string {
  return s.replace(/"/g, '\\"');
}

export function generateAppIntentShellSwift(
  intent: AppIntentHostConfig
): string {
  const openApp = intent.openAppWhenRun !== false;
  const description = intent.description
    ? `IntentDescription("${escapeSwiftString(intent.description)}")`
    : `IntentDescription("${escapeSwiftString(intent.title)}")`;

  return `import AppIntents
import Foundation

// @generated by expo-targets — DO NOT EDIT (ExpoTargetsGenerated)
struct ${intent.className}: AppIntent {
  static var title: LocalizedStringResource = "${escapeSwiftString(intent.title)}"
  static var description = ${description}
  static var openAppWhenRun: Bool = ${openApp ? 'true' : 'false'}

  func perform() async throws -> some IntentResult {
    try await ${intent.performHook}.perform()
    return .result()
  }
}
`;
}

export function generateAppShortcutsProviderSwift(
  providerName: string,
  shortcuts: AppShortcutConfig[]
): string {
  const entries = shortcuts
    .map((s) => {
      const phrases = s.phrases
        .map((p) => `"${escapeAppShortcutPhrase(p)}"`)
        .join(',\n        ');
      const image = s.systemImageName
        ? `systemImageName: "${escapeSwiftString(s.systemImageName)}"`
        : 'systemImageName: "app"';
      return `    AppShortcut(
      intent: ${s.intent}(),
      phrases: [
        ${phrases}
      ],
      shortTitle: "${escapeSwiftString(s.shortTitle)}",
      ${image}
    )`;
    })
    .join(',\n');

  // AppShortcutsProvider.appShortcuts uses @AppShortcutsBuilder — emit statements,
  // not a Swift Array literal (that fails type-check as [AppShortcut] vs AppShortcut).
  return `import AppIntents

// @generated by expo-targets — DO NOT EDIT (ExpoTargetsGenerated)
struct ${providerName}: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
${entries}
  }
}
`;
}

/** Minimal perform-hook stub for create-expo-target (user-owned, not regenerated). */
export function generatePerformHookStub(
  hookName: string,
  intentTitle: string
): string {
  return `import AppIntents
import Foundation

/// User-owned App Intent perform hook — safe to edit; prebuild will not overwrite.
enum ${hookName} {
  static func perform() async throws {
    // TODO: implement "${intentTitle}"
  }
}
`;
}
