import type { LiveActivityConfig } from '../../config';
import { jsonDecodeExpr, swiftTypeForField } from './swiftTypes';

function fieldsBlock(
  fields: Record<string, 'string' | 'double' | 'int' | 'bool'> | undefined,
  indent: string
): string {
  if (!fields || Object.keys(fields).length === 0) {
    return `${indent}// no fields`;
  }
  return Object.entries(fields)
    .map(([name, type]) => `${indent}var ${name}: ${swiftTypeForField(type)}`)
    .join('\n');
}

function decodeBlock(
  fields: Record<string, 'string' | 'double' | 'int' | 'bool'> | undefined,
  dictName: string,
  indent: string
): string {
  if (!fields || Object.keys(fields).length === 0) {
    return '';
  }
  return Object.entries(fields)
    .map(
      ([name, type]) =>
        `${indent}let ${name} = ${jsonDecodeExpr(dictName, name, type)}`
    )
    .join('\n');
}

function initArgs(
  fields: Record<string, 'string' | 'double' | 'int' | 'bool'> | undefined
): string {
  if (!fields || Object.keys(fields).length === 0) {
    return '';
  }
  return Object.keys(fields)
    .map((name) => `${name}: ${name}`)
    .join(', ');
}

/** ActivityAttributes Swift — shared by host + widget (dual membership). */
export function generateLiveActivityAttributesSwift(
  config: LiveActivityConfig
): string {
  const name = config.attributesName;
  const staticFields = config.static ?? {};
  const stateFields = config.contentState;

  return `import ActivityKit
import Foundation

// @generated by expo-targets — DO NOT EDIT (ExpoTargetsGenerated)
public struct ${name}: ActivityAttributes {
  public struct ContentState: Codable, Hashable {
${fieldsBlock(stateFields, '    ')}
  }

${fieldsBlock(staticFields, '  ')}
}
`;
}

/** Host bridge that registers with ExpoTargetsLiveActivityBridge. */
export function generateLiveActivityBridgeSwift(
  config: LiveActivityConfig
): string {
  const name = config.attributesName;
  const staticFields = config.static ?? {};
  const stateFields = config.contentState;
  const staticDecode = decodeBlock(staticFields, 'attrs', '      ');
  const stateDecode = decodeBlock(stateFields, 'state', '      ');
  const staticInit = initArgs(staticFields);
  const stateInit = initArgs(stateFields);
  const objcName = `ExpoTargetsLABridge_${name}`;

  return `import ActivityKit
import Foundation
internal import ExpoTargetsStorage

// @generated by expo-targets — DO NOT EDIT (ExpoTargetsGenerated)
private enum ${name}JSON {
  static func dict(from json: String) -> [String: Any] {
    guard let data = json.data(using: .utf8),
          let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
    else { return [:] }
    return obj
  }

  static func attributes(from json: String) -> ${name} {
    let attrs = dict(from: json)
${staticDecode}
    return ${name}(${staticInit})
  }

  static func contentState(from json: String) -> ${name}.ContentState {
    let state = dict(from: json)
${stateDecode}
    return ${name}.ContentState(${stateInit})
  }
}

private final class ${name}BridgeRegistration {
  static let shared = ${name}BridgeRegistration()

  init() {
    ExpoTargetsLiveActivityBridge.register(
      attributesName: "${name}",
      handler: ExpoTargetsLiveActivityBridge.Handler(
        start: { attributesJson, contentStateJson in
          guard #available(iOS 16.2, *) else {
            throw NSError(
              domain: "ExpoTargetsLiveActivity",
              code: 16,
              userInfo: [NSLocalizedDescriptionKey: "Live Activities require iOS 16.2+"]
            )
          }
          let attributes = ${name}JSON.attributes(from: attributesJson)
          let state = ${name}JSON.contentState(from: contentStateJson)
          let activity = try Activity.request(
            attributes: attributes,
            content: .init(state: state, staleDate: nil),
            pushType: ${config.pushType === 'token' ? '.token' : 'nil'}
          )
          return activity.id
        },
        update: { activityId, contentStateJson in
          guard #available(iOS 16.2, *) else { return false }
          guard let activity = Activity<${name}>.activities.first(where: { $0.id == activityId })
          else { return false }
          let state = ${name}JSON.contentState(from: contentStateJson)
          await activity.update(.init(state: state, staleDate: nil))
          return true
        },
        end: { activityId in
          guard #available(iOS 16.2, *) else { return }
          guard let activity = Activity<${name}>.activities.first(where: { $0.id == activityId })
          else { return }
          await activity.end(nil, dismissalPolicy: .immediate)
        },
        endAll: {
          guard #available(iOS 16.2, *) else { return }
          for activity in Activity<${name}>.activities {
            await activity.end(nil, dismissalPolicy: .immediate)
          }
        }
      )
    )
  }
}

/// ObjC + cdecl entry so ExpoTargetsLiveActivityModule can force-register
/// (file-level Swift statics / unused classes get linker-stripped in Release).
@objc(${objcName})
public final class ${objcName}: NSObject {
  @objc public static func ensureRegistered() {
    _ = ${name}BridgeRegistration.shared
  }
}

@used
@_cdecl("expo_targets_la_bootstrap_${name}")
public func expo_targets_la_bootstrap_${name}() {
  ${objcName}.ensureRegistered()
}
`;
}
