/**
 * Updates-shaped host API for sideloading extension bundles after expo-updates.
 * Does not run inside the appex. Optional peer: expo-updates.
 */

export type ExtensionBundleManifest = {
  byteLength: number;
  sha256: string;
  installedAt: string;
  runtimeVersion: string;
  targetName: string;
  type: string;
};

export type ExtensionUpdatesCheckResult = {
  isAvailable: boolean;
  manifest?: Record<string, unknown>;
  reason?: string;
};

export type ExtensionUpdatesFetchResult = {
  isNew: boolean;
  installed: ExtensionBundleManifest[];
  reason?: string;
};

type UpdatesLike = {
  checkForUpdateAsync: () => Promise<{
    isAvailable: boolean;
    manifest?: Record<string, unknown>;
    reason?: string;
  }>;
  fetchUpdateAsync: () => Promise<{
    isNew: boolean;
    manifest?: Record<string, unknown>;
  }>;
  reloadAsync: () => Promise<void>;
  runtimeVersion?: string | null;
};

export type ExtensionUpdatesSyncTarget = {
  targetName: string;
  type: string;
  runtimeVersion?: string;
};

export type ExtensionUpdatesOptions = {
  /** App Group id for native install (required unless `install` is injected). */
  appGroup?: string;
  /**
   * Metro asset module ids from `assets/expo-targets/extensionBundleModules.js`
   * (generated by `export-extension-bundles`). Used by default `resolveAssetPath`.
   */
  assetModules?: Record<string, number>;
  resolveAssetPath?: (
    targetName: string
  ) => string | null | Promise<string | null>;
  install?: (opts: {
    targetName: string;
    type: string;
    runtimeVersion: string;
    localPath: string;
  }) => Promise<ExtensionBundleManifest>;
  getUpdates?: () => UpdatesLike | null;
  targets: ExtensionUpdatesSyncTarget[];
};

function defaultGetUpdates(): UpdatesLike | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require('expo-updates') as UpdatesLike;
  } catch {
    return null;
  }
}

/**
 * Convert an expo-asset `localUri` into a filesystem path.
 * Must percent-decode: stripping only `file://` leaves `Application%20Support`
 * and native `fileExists` fails.
 */
export function fileUriToFsPath(uri: string): string {
  let path = uri;
  if (path.startsWith('file://')) {
    path = path.slice('file://'.length);
  }
  try {
    return decodeURIComponent(path);
  } catch {
    return path;
  }
}

function createDefaultResolveAssetPath(
  assetModules?: Record<string, number>
): (targetName: string) => Promise<string | null> {
  return async (targetName: string) => {
    const mod = assetModules?.[targetName];
    if (mod === undefined) {
      return null;
    }
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { Asset } = require('expo-asset') as {
        Asset: {
          fromModule: (m: number) => {
            downloadAsync: () => Promise<unknown>;
            localUri: string | null;
          };
        };
      };
      const asset = Asset.fromModule(mod);
      await asset.downloadAsync();
      const uri = asset.localUri;
      if (!uri) {
        return null;
      }
      return fileUriToFsPath(uri);
    } catch {
      return null;
    }
  };
}

function createDefaultInstall(
  appGroup: string | undefined
): NonNullable<ExtensionUpdatesOptions['install']> {
  return async ({ targetName, type, runtimeVersion, localPath }) => {
    if (!appGroup) {
      throw new Error(
        'createExtensionUpdates: pass appGroup (or a custom install) to sync into the App Group'
      );
    }
    // Lazy: avoid pulling expo-modules-core / RN into Node unit tests.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { installExtensionBundleNative } = require('./nativeInstall') as {
      installExtensionBundleNative: (opts: {
        appGroup: string;
        targetName: string;
        type: string;
        runtimeVersion: string;
        localPath: string;
      }) => Promise<ExtensionBundleManifest>;
    };
    return installExtensionBundleNative({
      appGroup,
      targetName,
      type,
      runtimeVersion,
      localPath,
    });
  };
}

export function createExtensionUpdates(options: ExtensionUpdatesOptions) {
  const getUpdates = options.getUpdates ?? defaultGetUpdates;
  const resolveAssetPath =
    options.resolveAssetPath ??
    createDefaultResolveAssetPath(options.assetModules);
  const install = options.install ?? createDefaultInstall(options.appGroup);

  async function syncInstalledTargets(
    runtimeVersion: string
  ): Promise<ExtensionBundleManifest[]> {
    const installed: ExtensionBundleManifest[] = [];
    for (const t of options.targets) {
      const localPath = await resolveAssetPath(t.targetName);
      if (!localPath) {
        continue;
      }
      const rv = t.runtimeVersion ?? runtimeVersion;
      if (!rv) {
        throw new Error(
          `runtimeVersion required to sync extension bundle "${t.targetName}"`
        );
      }
      installed.push(
        await install({
          targetName: t.targetName,
          type: t.type,
          runtimeVersion: rv,
          localPath,
        })
      );
    }
    return installed;
  }

  return buildExtensionUpdatesApi({
    getUpdates,
    syncInstalledTargets,
  });
}

async function extensionUpdatesFetch(deps: {
  getUpdates: () => UpdatesLike | null;
  syncInstalledTargets: (
    runtimeVersion: string
  ) => Promise<ExtensionBundleManifest[]>;
}): Promise<ExtensionUpdatesFetchResult> {
  const Updates = deps.getUpdates();
  if (!Updates) {
    return {
      isNew: false,
      installed: [],
      reason: 'expo-updates is not installed',
    };
  }
  const result = await Updates.fetchUpdateAsync();
  const runtimeVersion =
    Updates.runtimeVersion ??
    (typeof result.manifest?.runtimeVersion === 'string'
      ? result.manifest.runtimeVersion
      : '');
  if (!result.isNew) {
    return { isNew: false, installed: [] };
  }
  if (!runtimeVersion) {
    throw new Error(
      'runtimeVersion unresolved after fetchUpdateAsync — fail closed'
    );
  }
  const installed = await deps.syncInstalledTargets(runtimeVersion);
  return { isNew: true, installed };
}

function buildExtensionUpdatesApi(deps: {
  getUpdates: () => UpdatesLike | null;
  syncInstalledTargets: (
    runtimeVersion: string
  ) => Promise<ExtensionBundleManifest[]>;
}) {
  async function checkForUpdateAsync(): Promise<ExtensionUpdatesCheckResult> {
    const Updates = deps.getUpdates();
    if (!Updates) {
      return {
        isAvailable: false,
        reason: 'expo-updates is not installed',
      };
    }
    const result = await Updates.checkForUpdateAsync();
    return {
      isAvailable: result.isAvailable,
      manifest: result.manifest,
      reason: result.reason,
    };
  }

  async function reloadAsync(): Promise<void> {
    const Updates = deps.getUpdates();
    if (!Updates) {
      throw new Error('expo-updates is not installed');
    }
    await Updates.reloadAsync();
  }

  return {
    checkForUpdateAsync,
    fetchUpdateAsync: () => extensionUpdatesFetch(deps),
    reloadAsync,
    syncFromCurrentUpdate: async () => {
      const Updates = deps.getUpdates();
      const runtimeVersion = Updates?.runtimeVersion ?? '';
      if (!runtimeVersion) {
        throw new Error('runtimeVersion unresolved — fail closed');
      }
      return deps.syncInstalledTargets(runtimeVersion);
    },
  };
}
