import { describe, expect, test } from 'bun:test';

import { formatTargetsTypesFile } from './typedTargets';

describe('formatTargetsTypesFile', () => {
  test('emits Targets keyed by config.name', () => {
    const content = formatTargetsTypesFile([
      { name: 'MyShare' },
      { name: 'MyAction' },
    ]);
    expect(content).toContain('// @generated by expo-targets — do not edit');
    expect(content).toContain("MyAction: 'MyAction'");
    expect(content).toContain("MyShare: 'MyShare'");
    expect(content).toContain('export type TargetName');
    expect(content).not.toContain('displayName');
  });

  test('dedupes target names and sorts keys', () => {
    const content = formatTargetsTypesFile([
      { name: 'Zeta' },
      { name: 'Alpha' },
      { name: 'Zeta' },
    ]);
    expect(content.indexOf('Alpha')).toBeLessThan(content.indexOf('Zeta'));
    expect(content.match(/Zeta/g)?.length).toBe(2);
  });

  test('emits LiveActivityAttributes when attributesName is set', () => {
    const content = formatTargetsTypesFile([
      {
        name: 'WeatherWidget',
        liveActivity: { attributesName: 'WeatherAttributes' },
      },
    ]);
    expect(content).toContain('export const LiveActivityAttributes');
    expect(content).toContain("WeatherAttributes: 'WeatherAttributes'");
    expect(content).toContain('export type LiveActivityAttributesName');
  });

  test('omits LiveActivityAttributes when no live activities', () => {
    const content = formatTargetsTypesFile([{ name: 'Share' }]);
    expect(content).not.toContain('LiveActivityAttributes');
  });
});
