import fs from 'node:fs';
import path from 'node:path';

/** Ambient decls (Expo Router–style). Gitignored under `.expo/`. */
export const GENERATED_RELATIVE_PATH = '.expo/types/expo-targets.d.ts';

const LEGACY_GENERATED_RELATIVE_PATH = '.expo/expo-targets.generated.ts';

const GENERATED_HEADER =
  '// @generated by expo-targets — do not edit\n' +
  '// Loaded automatically when tsconfig has no include (expo/tsconfig.base).\n' +
  '// If include is already set, generate appends ".expo/types/**/*.ts" when missing.\n';

export type LiveActivityFieldType = 'string' | 'double' | 'int' | 'bool';

export interface TargetCodegenConfig {
  name: string;
  /** Gallery kind / provider names (defaults to folder name when omitted). */
  widgetKinds?: string[];
  liveActivity?: {
    attributesName?: string;
    static?: Record<string, LiveActivityFieldType>;
    contentState?: Record<string, LiveActivityFieldType>;
  };
}

function interfaceMembers(keys: string[]): string {
  if (keys.length === 0) {
    return '';
  }
  return `${keys.map((key) => `    ${JSON.stringify(key)}: true;`).join('\n')}\n`;
}

function mapFieldType(t: LiveActivityFieldType | string): string {
  switch (t) {
    case 'double':
    case 'int':
      return 'number';
    case 'bool':
      return 'boolean';
    default:
      return 'string';
  }
}

function formatRecordFields(
  fields: Record<string, LiveActivityFieldType | string> | undefined
): string {
  if (!fields || Object.keys(fields).length === 0) {
    return 'Record<string, string | number | boolean>';
  }
  const body = Object.keys(fields)
    .sort()
    .map((key) => `      ${JSON.stringify(key)}: ${mapFieldType(fields[key])};`)
    .join('\n');
  return `{\n${body}\n    }`;
}

function formatPayloadRegistry(liveActivities: TargetCodegenConfig[]): string {
  const payloadEntries = new Map<
    string,
    {
      static?: Record<string, LiveActivityFieldType>;
      contentState?: Record<string, LiveActivityFieldType>;
    }
  >();
  for (const cfg of liveActivities) {
    const attr = cfg.liveActivity?.attributesName;
    if (!attr) {
      continue;
    }
    payloadEntries.set(attr, {
      static: cfg.liveActivity?.static,
      contentState: cfg.liveActivity?.contentState,
    });
  }

  if (payloadEntries.size === 0) {
    return '';
  }

  let body = `  interface LiveActivityPayloadRegistry {\n`;
  for (const attr of [...payloadEntries.keys()].sort()) {
    const fields = payloadEntries.get(attr)!;
    body += `    ${JSON.stringify(attr)}: {\n`;
    body += `      attributes: ${formatRecordFields(fields.static)};\n`;
    body += `      contentState: ${formatRecordFields(fields.contentState)};\n`;
    body += `    };\n`;
  }
  body += `  }\n`;
  return body;
}

/**
 * Ambient module augmentation for `expo-targets`.
 * Narrows TargetName / LiveActivityAttributesName and LA payload shapes.
 */
export function formatTargetsTypesFile(configs: TargetCodegenConfig[]): string {
  const names = [...new Set(configs.map((c) => c.name).filter(Boolean))].sort();
  const widgetKindNames = [
    ...new Set(
      configs.flatMap((c) => c.widgetKinds ?? (c.name ? [c.name] : [])).filter(Boolean)
    ),
  ].sort();
  const liveActivities = configs.filter((c) => c.liveActivity?.attributesName);
  const attributesNames = [
    ...new Set(
      liveActivities
        .map((c) => c.liveActivity?.attributesName)
        .filter((name): name is string => Boolean(name))
    ),
  ].sort();

  let content = GENERATED_HEADER;
  content += `declare module 'expo-targets' {\n`;
  content += `  interface KnownTargets {\n`;
  content += interfaceMembers(names);
  content += `  }\n`;
  content += `  interface KnownWidgetKinds {\n`;
  content += interfaceMembers(widgetKindNames);
  content += `  }\n`;
  content += `  interface KnownLiveActivityAttributes {\n`;
  content += interfaceMembers(attributesNames);
  content += `  }\n`;
  content += formatPayloadRegistry(liveActivities);
  content += `}\n`;
  content += `\nexport {};\n`;
  return content;
}

const EXPO_TYPES_INCLUDE = '.expo/types/**/*.ts';

function includeAlreadyCoversExpoTypes(include: string[]): boolean {
  return (
    include.includes(EXPO_TYPES_INCLUDE) || include.includes('.expo/types/**/*')
  );
}

/**
 * Append the Expo types glob only when `include` already exists.
 * Apps that only extend `expo/tsconfig.base` (no include) already pick up
 * `.expo/types/*.d.ts` via TS defaults — inventing include would exclude app sources.
 */
export function ensureTsconfigExpoTypesInclude(projectRoot: string): boolean {
  const tsconfigPath = path.join(projectRoot, 'tsconfig.json');
  if (!fs.existsSync(tsconfigPath)) {
    return false;
  }

  let parsed: { include?: string[] };
  try {
    const raw = fs.readFileSync(tsconfigPath, 'utf8');
    const jsonish = raw.replace(/^\s*\/\/.*$/gm, '');
    parsed = JSON.parse(jsonish) as { include?: string[] };
  } catch {
    return false;
  }

  const include = parsed.include;
  if (!Array.isArray(include) || include.length === 0) {
    return false;
  }
  if (includeAlreadyCoversExpoTypes(include)) {
    return false;
  }

  parsed.include = [...include, EXPO_TYPES_INCLUDE];
  fs.writeFileSync(tsconfigPath, `${JSON.stringify(parsed, null, 2)}\n`);
  return true;
}

export function writeTargetsTypesFile(
  projectRoot: string,
  configs: TargetCodegenConfig[]
): string {
  const filePath = path.join(projectRoot, GENERATED_RELATIVE_PATH);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, formatTargetsTypesFile(configs));

  const legacy = path.join(projectRoot, LEGACY_GENERATED_RELATIVE_PATH);
  if (fs.existsSync(legacy)) {
    fs.rmSync(legacy);
  }

  ensureTsconfigExpoTypesInclude(projectRoot);
  return filePath;
}
