import fs from 'node:fs';
import path from 'node:path';

export const GENERATED_RELATIVE_PATH = '.expo/expo-targets.generated.ts';

const GENERATED_HEADER = '// @generated by expo-targets — do not edit\n';

export interface TargetCodegenConfig {
  name: string;
  liveActivity?: { attributesName?: string };
}

function constObject(
  exportName: string,
  typeExportName: string,
  entries: [string, string][]
): string {
  if (entries.length === 0) {
    return '';
  }
  const body = entries
    .map(([key, value]) => `  ${key}: '${value}',`)
    .join('\n');
  return (
    `export const ${exportName} = {\n${body}\n} as const;\n` +
    `export type ${typeExportName} = typeof ${exportName}[keyof typeof ${exportName}];\n`
  );
}

export function formatTargetsTypesFile(configs: TargetCodegenConfig[]): string {
  const names = [...new Set(configs.map((c) => c.name).filter(Boolean))].sort();

  const attributesNames = [
    ...new Set(
      configs
        .map((c) => c.liveActivity?.attributesName)
        .filter((name): name is string => Boolean(name))
    ),
  ].sort();

  let content = GENERATED_HEADER;
  content += constObject(
    'Targets',
    'TargetName',
    names.map((name) => [name, name])
  );
  content += constObject(
    'LiveActivityAttributes',
    'LiveActivityAttributesName',
    attributesNames.map((name) => [name, name])
  );
  return content;
}

export function writeTargetsTypesFile(
  projectRoot: string,
  configs: TargetCodegenConfig[]
): string {
  const filePath = path.join(projectRoot, GENERATED_RELATIVE_PATH);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, formatTargetsTypesFile(configs));
  return filePath;
}
