import { describe, expect, test } from 'bun:test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import {
  ensureTsconfigExpoTypesInclude,
  formatTargetsTypesFile,
  GENERATED_RELATIVE_PATH,
  writeTargetsTypesFile,
} from './typedTargets';

describe('formatTargetsTypesFile', () => {
  test('emits ambient KnownTargets keyed by config.name', () => {
    const content = formatTargetsTypesFile([
      { name: 'MyShare' },
      { name: 'MyAction' },
    ]);
    expect(content).toContain('// @generated by expo-targets — do not edit');
    expect(content).toContain("declare module 'expo-targets'");
    expect(content).toContain('interface KnownTargets');
    expect(content).toContain('"MyAction": true');
    expect(content).toContain('"MyShare": true');
    expect(content).not.toContain('export const Targets');
    expect(content).not.toContain('displayName');
  });

  test('dedupes target names and sorts keys', () => {
    const content = formatTargetsTypesFile([
      { name: 'Zeta' },
      { name: 'Alpha' },
      { name: 'Zeta' },
    ]);
    expect(content.indexOf('"Alpha"')).toBeLessThan(content.indexOf('"Zeta"'));
    expect(content.match(/"Zeta"/g)?.length).toBe(1);
  });

  test('emits KnownLiveActivityAttributes when attributesName is set', () => {
    const content = formatTargetsTypesFile([
      {
        name: 'WeatherWidget',
        liveActivity: { attributesName: 'WeatherAttributes' },
      },
    ]);
    expect(content).toContain('interface KnownLiveActivityAttributes');
    expect(content).toContain('"WeatherAttributes": true');
  });

  test('omits attribute members when no live activities', () => {
    const content = formatTargetsTypesFile([{ name: 'Share' }]);
    expect(content).toContain('interface KnownLiveActivityAttributes');
    expect(content).not.toContain('WeatherAttributes');
  });
});

describe('writeTargetsTypesFile', () => {
  test('writes .expo/types/expo-targets.d.ts and removes legacy module', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'typed-targets-'));
    try {
      const legacy = path.join(root, '.expo', 'expo-targets.generated.ts');
      fs.mkdirSync(path.dirname(legacy), { recursive: true });
      fs.writeFileSync(legacy, 'export const Targets = {};\n');
      fs.writeFileSync(
        path.join(root, 'tsconfig.json'),
        JSON.stringify({ include: ['**/*.ts'] })
      );

      const out = writeTargetsTypesFile(root, [{ name: 'Share' }]);
      expect(out).toBe(path.join(root, GENERATED_RELATIVE_PATH));
      expect(fs.existsSync(out)).toBe(true);
      expect(fs.existsSync(legacy)).toBe(false);
      const tsconfig = JSON.parse(
        fs.readFileSync(path.join(root, 'tsconfig.json'), 'utf8')
      ) as { include: string[] };
      expect(tsconfig.include).toContain('.expo/types/**/*.ts');
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  test('ensureTsconfigExpoTypesInclude is idempotent', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'typed-tsconfig-'));
    try {
      fs.writeFileSync(
        path.join(root, 'tsconfig.json'),
        JSON.stringify({ include: ['.expo/types/**/*.ts'] })
      );
      expect(ensureTsconfigExpoTypesInclude(root)).toBe(false);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });
});
