import fs from 'node:fs';
import path from 'node:path';

const GENERATED_MARKERS = [
  '@generated',
  'DO NOT EDIT',
  'Generated by expo-targets',
];

export interface SealedWarnLogger {
  warn(message: string): void;
}

export type WarnSealedOptions = {
  filePath: string;
  plannedContent: string;
  logger: SealedWarnLogger;
  userDeepenPath?: string;
};

export function isGeneratedSealedContent(content: string): boolean {
  return GENERATED_MARKERS.some((marker) => content.includes(marker));
}

export function warnIfSealedHandEdited(options: WarnSealedOptions): void {
  const {
    filePath,
    plannedContent,
    logger,
    userDeepenPath = 'targets/<name>/ios/',
  } = options;
  if (!fs.existsSync(filePath)) {
    return;
  }

  const existing = fs.readFileSync(filePath, 'utf8');
  if (existing === plannedContent || isGeneratedSealedContent(existing)) {
    return;
  }

  const rel = path.basename(filePath);
  logger.warn(
    `Hand-edited sealed file will be overwritten: ${rel}. ` +
      `Move customizations to ${userDeepenPath}`
  );
}
