import { afterEach, describe, expect, test } from 'bun:test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import {
  isGeneratedSealedContent,
  warnIfSealedHandEdited,
} from './warnIfSealedHandEdited';

const files: string[] = [];

function tempFile(content: string): string {
  const filePath = path.join(
    os.tmpdir(),
    `expo-targets-sealed-${Date.now()}-${Math.random()}.txt`
  );
  fs.writeFileSync(filePath, content);
  files.push(filePath);
  return filePath;
}

afterEach(() => {
  for (const filePath of files.splice(0)) {
    fs.rmSync(filePath, { force: true });
  }
});

describe('isGeneratedSealedContent', () => {
  test('detects expo-targets generated markers', () => {
    expect(
      isGeneratedSealedContent('// @generated by expo-targets — DO NOT EDIT')
    ).toBe(true);
    expect(isGeneratedSealedContent('Generated by expo-targets')).toBe(true);
    expect(isGeneratedSealedContent('hand-written swift')).toBe(false);
  });
});

describe('warnIfSealedHandEdited', () => {
  test('warns on hand-edited content that differs from planned', () => {
    const filePath = tempFile('user edits');
    const warnings: string[] = [];
    warnIfSealedHandEdited({
      filePath,
      plannedContent: 'planned',
      logger: { warn: (m) => warnings.push(m) },
    });
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain('Hand-edited sealed file');
    expect(warnings[0]).toContain('targets/<name>/ios/');
  });

  test('does not warn when content matches planned', () => {
    const filePath = tempFile('planned');
    const warnings: string[] = [];
    warnIfSealedHandEdited({
      filePath,
      plannedContent: 'planned',
      logger: { warn: (m) => warnings.push(m) },
    });
    expect(warnings).toHaveLength(0);
  });

  test('does not warn when existing file has generated marker', () => {
    const filePath = tempFile('// @generated by expo-targets\nstale');
    const warnings: string[] = [];
    warnIfSealedHandEdited({
      filePath,
      plannedContent: 'new planned',
      logger: { warn: (m) => warnings.push(m) },
    });
    expect(warnings).toHaveLength(0);
  });
});
