/**
 * Host/extension contracts for REQUIRED_V1 journeys.
 * Bundle IDs / markers mirror ios-harness matrix defaults.
 */

export type TargetCatalogEntry = {
  id: string;
  path: string;
  hostBundleId: string;
  /**
   * Android applicationId when it must diverge from iOS `hostBundleId`
   * (hyphens are valid in Apple bundle IDs, not in Android packages).
   */
  androidPackage?: string;
  hostDisplayName: string;
  extensionName: string;
  extensionAliases: string[];
  payloadMarker: string;
  readyText?: string;
  completeButton: string;
  /** Expand share-sheet action list before looking for the row. */
  needsViewMore?: boolean;
  /** Host testIDs expected for C1 / A bars. */
  testIds: {
    screenRoot: string;
    openShareSheet?: string;
    clearPayload: string;
    refresh?: string;
    lastPayload: string;
    packCatalog?: string;
  };
};

const SHARE_TEST_IDS = {
  screenRoot: "screen-root",
  openShareSheet: "btn-open-share-sheet",
  clearPayload: "btn-clear-payload",
  refresh: "btn-refresh",
  lastPayload: "text-last-payload",
} as const;

export const TARGET_CATALOG: Record<string, TargetCatalogEntry> = {
  share: {
    id: "share",
    path: "examples/share",
    hostBundleId: "com.expotargets.example.share",
    hostDisplayName: "ET Share",
    extensionName: "ET Share",
    extensionAliases: ["ExampleShareTarget", "Example Share", "Share"],
    payloadMarker: "expo-targets uitest share payload",
    readyText: "expo-targets uitest share payload",
    completeButton: "Save",
    testIds: { ...SHARE_TEST_IDS },
  },
  action: {
    id: "action",
    path: "examples/action",
    hostBundleId: "com.expotargets.example.action",
    hostDisplayName: "ET Action",
    extensionName: "Example Action",
    extensionAliases: ["ExampleActionTarget", "ET Action"],
    payloadMarker: "grayscale",
    readyText: "Images: 1",
    completeButton: "Process",
    needsViewMore: true,
    testIds: { ...SHARE_TEST_IDS },
  },
  "native-share": {
    id: "native-share",
    path: "examples/native/share",
    hostBundleId: "com.expotargets.example.native.share",
    androidPackage: "com.expotargets.example.nativeshare",
    hostDisplayName: "ET N Share",
    extensionName: "ET N Share",
    extensionAliases: ["NativeShareTarget", "Native Share"],
    payloadMarker: "expo-targets uitest share payload",
    readyText: "expo-targets uitest share payload",
    completeButton: "Save to App",
    testIds: { ...SHARE_TEST_IDS },
  },
  "native-action": {
    id: "native-action",
    path: "examples/native/action",
    hostBundleId: "com.expotargets.example.native.action",
    androidPackage: "com.expotargets.example.nativeaction",
    hostDisplayName: "ET N Action",
    extensionName: "Native Action",
    extensionAliases: ["NativeActionTarget", "ET N Action"],
    payloadMarker: "Original",
    readyText: "Original",
    completeButton: "Process Image",
    needsViewMore: true,
    testIds: { ...SHARE_TEST_IDS },
  },
  messages: {
    id: "messages",
    path: "examples/messages",
    hostBundleId: "com.expotargets.example.messages",
    hostDisplayName: "ET Messages",
    extensionName: "Example Messages",
    extensionAliases: ["ExampleMessagesTarget", "ET Messages"],
    payloadMarker: "Hello from expo-targets",
    completeButton: "Send template",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      refresh: "btn-refresh",
      lastPayload: "text-last-payload",
    },
  },
  stickers: {
    id: "stickers",
    path: "examples/stickers",
    hostBundleId: "com.expotargets.example.stickers",
    hostDisplayName: "ET Stickers",
    extensionName: "Fun Stickers",
    extensionAliases: ["FunStickersTarget", "Fun Stickers"],
    /** Honest pack catalog marker (asset-only packs cannot App-Group on selection). */
    payloadMarker:
      "pack: Fun Stickers (bip, wave, hug, peek, jump, sit, heart)",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
      packCatalog: "status-pack-catalog",
    },
  },
  clip: {
    id: "clip",
    path: "examples/clip",
    hostBundleId: "com.expotargets.example.clip",
    hostDisplayName: "ET Clip",
    extensionName: "Clip",
    extensionAliases: [],
    payloadMarker: "itemName",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  widgets: {
    id: "widgets",
    path: "examples/widgets",
    hostBundleId: "com.expotargets.example.widgets",
    hostDisplayName: "ET Widgets",
    extensionName: "Hello Widget",
    extensionAliases: [],
    payloadMarker: "Hello from host · family:systemSmall",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "widgets-expo-ui": {
    id: "widgets-expo-ui",
    path: "examples/widgets",
    hostBundleId: "com.expotargets.example.widgets",
    hostDisplayName: "ET Widgets",
    extensionName: "Hello Expo UI",
    extensionAliases: ["HelloExpoUi", "Hello Expo UI"],
    payloadMarker: "Hello from host · expo-ui",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-expo-ui-payload",
    },
  },
  "widgets-remoteviews": {
    id: "widgets-remoteviews",
    path: "examples/widgets",
    hostBundleId: "com.expotargets.example.widgets",
    hostDisplayName: "ET Widgets",
    extensionName: "Hello RemoteViews",
    extensionAliases: ["HelloRemoteViews", "Hello RemoteViews"],
    payloadMarker: "Hello from host · remoteviews",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-remoteviews-payload",
    },
  },
  "live-activity": {
    id: "live-activity",
    path: "examples/trick",
    hostBundleId: "com.expotargets.example.trick",
    hostDisplayName: "ET Trick",
    extensionName: "ET Trick Widget",
    extensionAliases: ["ET Trick Widget", "TrickWidget"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "status-target-ready",
      clearPayload: "btn-end-live",
      lastPayload: "text-live-id",
    },
  },

  "notification-service": {
    id: "notification-service",
    path: "examples/notification-service",
    hostBundleId: "com.expotargets.example.notification-service",
    androidPackage: "com.expotargets.example.notificationservice",
    hostDisplayName: "ET NSE",
    extensionName: "ET NSE Target",
    extensionAliases: ["ET NSE Target", "notification-service"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "notification-content": {
    id: "notification-content",
    path: "examples/notification-content",
    hostBundleId: "com.expotargets.example.notification-content",
    androidPackage: "com.expotargets.example.notificationcontent",
    hostDisplayName: "ET NCE",
    extensionName: "ET NCE Target",
    extensionAliases: ["ET NCE Target", "notification-content"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "native-notification-content": {
    id: "native-notification-content",
    path: "examples/native/notification-content",
    hostBundleId: "com.expotargets.example.native.notification-content",
    androidPackage: "com.expotargets.example.nativenotificationcontent",
    hostDisplayName: "ET NCE N",
    extensionName: "ET NCE Target",
    extensionAliases: ["ET NCE Target", "native-notification-content"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  wallet: {
    id: "wallet",
    path: "examples/wallet",
    hostBundleId: "com.expotargets.example.wallet",
    hostDisplayName: "ET wallet",
    extensionName: "ET wallet",
    extensionAliases: ["wallet"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "wallet-ui": {
    id: "wallet-ui",
    path: "examples/wallet",
    hostBundleId: "com.expotargets.example.wallet",
    hostDisplayName: "ET wallet",
    extensionName: "ET Wallet Auth",
    extensionAliases: ["wallet-ui", "Wallet Auth"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "native-clip": {
    id: "native-clip",
    path: "examples/native/clip",
    hostBundleId: "com.expotargets.example.native.clip",
    hostDisplayName: "ET N Clip",
    extensionName: "Native Clip",
    extensionAliases: ["Native Clip", "native-clip"],
    payloadMarker: "itemName",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  safari: {
    id: "safari",
    path: "examples/safari",
    hostBundleId: "com.expotargets.example.safari",
    hostDisplayName: "ET Safari",
    extensionName: "ET Safari Target",
    extensionAliases: ["ET Safari Target", "Safari", "safari"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "native-safari": {
    id: "native-safari",
    path: "examples/native/safari",
    hostBundleId: "com.expotargets.example.native.safari",
    hostDisplayName: "ET Safari N",
    extensionName: "ET Safari Target",
    extensionAliases: ["ET Safari Target", "NativeSafari", "native-safari"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "content-blocker": {
    id: "content-blocker",
    path: "examples/content-blocker",
    hostBundleId: "com.expotargets.example.content-blocker",
    hostDisplayName: "ET Blocker",
    extensionName: "ET Blocker Target",
    extensionAliases: ["ET Blocker Target", "content-blocker"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "app-intent": {
    id: "app-intent",
    path: "examples/app-intent",
    hostBundleId: "com.expotargets.example.app-intent",
    androidPackage: "com.expotargets.example.appintent",
    hostDisplayName: "ET AppIntent",
    extensionName: "ET AppIntent Target",
    extensionAliases: ["ET AppIntent Target", "app-intent"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  intent: {
    id: "intent",
    path: "examples/intent",
    hostBundleId: "com.expotargets.example.intent",
    hostDisplayName: "ET Intent",
    extensionName: "ET Intent Target",
    extensionAliases: ["ET Intent Target", "intent"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "intent-ui": {
    id: "intent-ui",
    path: "examples/intent",
    hostBundleId: "com.expotargets.example.intent",
    hostDisplayName: "ET Intent",
    extensionName: "ET Intent UI",
    extensionAliases: ["intent-ui", "Intent UI"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "credentials-provider": {
    id: "credentials-provider",
    path: "examples/credentials-provider",
    hostBundleId: "com.expotargets.example.credentials-provider",
    androidPackage: "com.expotargets.example.credentialsprovider",
    hostDisplayName: "ET Creds",
    extensionName: "ET Creds Target",
    extensionAliases: ["ET Creds Target", "ET Creds", "credentials-provider"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "account-auth": {
    id: "account-auth",
    path: "examples/account-auth",
    hostBundleId: "com.expotargets.example.account-auth",
    hostDisplayName: "ET account-auth",
    extensionName: "ET account-auth",
    extensionAliases: ["account-auth"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "authentication-services": {
    id: "authentication-services",
    path: "examples/authentication-services",
    hostBundleId: "com.expotargets.example.authentication-services",
    hostDisplayName: "ET authentication-services",
    extensionName: "ET authentication-services",
    extensionAliases: ["authentication-services"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "photo-editing": {
    id: "photo-editing",
    path: "examples/photo-editing",
    hostBundleId: "com.expotargets.example.photo-editing",
    androidPackage: "com.expotargets.example.photoediting",
    hostDisplayName: "ET PhotoEdit",
    extensionName: "ET PhotoEdit Target",
    extensionAliases: ["ET PhotoEdit Target", "photo-editing"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "file-provider": {
    id: "file-provider",
    path: "examples/file-provider",
    hostBundleId: "com.expotargets.example.file-provider",
    androidPackage: "com.expotargets.example.fileprovider",
    hostDisplayName: "ET FileProv",
    extensionName: "ET FileProv Target",
    extensionAliases: ["ET FileProv Target", "file-provider"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      refresh: "btn-refresh",
      lastPayload: "text-last-payload",
    },
  },
  "file-provider-ui": {
    id: "file-provider-ui",
    path: "examples/file-provider-ui",
    hostBundleId: "com.expotargets.example.file-provider-ui",
    androidPackage: "com.expotargets.example.fileproviderui",
    hostDisplayName: "ET FileProvUI",
    extensionName: "ET FileProvUI Target",
    extensionAliases: ["ET FileProvUI Target", "file-provider-ui"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "quicklook-thumbnail": {
    id: "quicklook-thumbnail",
    path: "examples/quicklook-thumbnail",
    hostBundleId: "com.expotargets.example.quicklook-thumbnail",
    hostDisplayName: "ET QLThumb",
    extensionName: "ET QLThumb Target",
    extensionAliases: ["ET QLThumb Target", "quicklook-thumbnail"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "quicklook-preview": {
    id: "quicklook-preview",
    path: "examples/quicklook-preview",
    hostBundleId: "com.expotargets.example.quicklook-preview",
    hostDisplayName: "ET QLPreview",
    extensionName: "ET QLPreview Target",
    extensionAliases: ["ET QLPreview Target", "quicklook-preview"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "call-directory": {
    id: "call-directory",
    path: "examples/call-directory",
    hostBundleId: "com.expotargets.example.call-directory",
    androidPackage: "com.expotargets.example.calldirectory",
    hostDisplayName: "ET CallDir",
    extensionName: "ET CallDir Target",
    extensionAliases: ["ET CallDir Target", "ET CallDir", "call-directory"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "message-filter": {
    id: "message-filter",
    path: "examples/message-filter",
    hostBundleId: "com.expotargets.example.message-filter",
    androidPackage: "com.expotargets.example.messagefilter",
    hostDisplayName: "ET MsgFilter",
    extensionName: "ET MsgFilter Target",
    extensionAliases: ["ET MsgFilter Target", "message-filter"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "unwanted-communication": {
    id: "unwanted-communication",
    path: "examples/unwanted-communication",
    hostBundleId: "com.expotargets.example.unwanted-communication",
    androidPackage: "com.expotargets.example.unwantedcommunication",
    hostDisplayName: "ET Unwanted",
    extensionName: "ET Unwanted Target",
    extensionAliases: ["ET Unwanted Target", "unwanted-communication"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  keyboard: {
    id: "keyboard",
    path: "examples/keyboard",
    hostBundleId: "com.expotargets.example.keyboard",
    hostDisplayName: "ET Keyboard",
    extensionName: "ET Keyboard Target",
    extensionAliases: ["ET Keyboard Target", "keyboard"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "broadcast-upload": {
    id: "broadcast-upload",
    path: "examples/broadcast-upload",
    hostBundleId: "com.expotargets.example.broadcast-upload",
    hostDisplayName: "ET Broadcast",
    extensionName: "ET Broadcast Target",
    extensionAliases: ["ET Broadcast Target", "broadcast-upload"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "broadcast-setup-ui": {
    id: "broadcast-setup-ui",
    path: "examples/broadcast-setup-ui",
    hostBundleId: "com.expotargets.example.broadcast-setup-ui",
    hostDisplayName: "ET BroadcastUI",
    extensionName: "ET BroadcastUI Target",
    extensionAliases: ["ET BroadcastUI Target", "broadcast-setup-ui"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "device-activity-monitor": {
    id: "device-activity-monitor",
    path: "examples/device-activity-monitor",
    hostBundleId: "com.expotargets.example.device-activity-monitor",
    hostDisplayName: "ET device-activity-monitor",
    extensionName: "ET device-activity-monitor",
    extensionAliases: ["device-activity-monitor"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "shield-action": {
    id: "shield-action",
    path: "examples/shield-action",
    hostBundleId: "com.expotargets.example.shield-action",
    hostDisplayName: "ET shield-action",
    extensionName: "ET shield-action",
    extensionAliases: ["shield-action"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "shield-config": {
    id: "shield-config",
    path: "examples/shield-config",
    hostBundleId: "com.expotargets.example.shield-config",
    hostDisplayName: "ET shield-config",
    extensionName: "ET shield-config",
    extensionAliases: ["shield-config"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "network-packet-tunnel": {
    id: "network-packet-tunnel",
    path: "examples/network-packet-tunnel",
    hostBundleId: "com.expotargets.example.network-packet-tunnel",
    androidPackage: "com.expotargets.example.networkpackettunnel",
    hostDisplayName: "ET NETunnel",
    extensionName: "ET NETunnel Target",
    extensionAliases: ["ET NETunnel Target", "ET NETunnel", "network-packet-tunnel"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "network-app-proxy": {
    id: "network-app-proxy",
    path: "examples/network-app-proxy",
    hostBundleId: "com.expotargets.example.network-app-proxy",
    hostDisplayName: "ET network-app-proxy",
    extensionName: "ET network-app-proxy",
    extensionAliases: ["network-app-proxy"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "network-dns-proxy": {
    id: "network-dns-proxy",
    path: "examples/network-dns-proxy",
    hostBundleId: "com.expotargets.example.network-dns-proxy",
    hostDisplayName: "ET network-dns-proxy",
    extensionName: "ET network-dns-proxy",
    extensionAliases: ["network-dns-proxy"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "network-filter-data": {
    id: "network-filter-data",
    path: "examples/network-filter-data",
    hostBundleId: "com.expotargets.example.network-filter-data",
    hostDisplayName: "ET network-filter-data",
    extensionName: "ET network-filter-data",
    extensionAliases: ["network-filter-data"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  spotlight: {
    id: "spotlight",
    path: "examples/spotlight",
    hostBundleId: "com.expotargets.example.spotlight",
    hostDisplayName: "ET Spotlight",
    extensionName: "ET Spotlight Target",
    extensionAliases: ["ET Spotlight Target", "spotlight"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "spotlight-delegate": {
    id: "spotlight-delegate",
    path: "examples/spotlight-delegate",
    hostBundleId: "com.expotargets.example.spotlight-delegate",
    androidPackage: "com.expotargets.example.spotlightdelegate",
    hostDisplayName: "ET SpotDel",
    extensionName: "ET SpotDel Target",
    extensionAliases: ["ET SpotDel Target", "spotlight-delegate"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "bg-download": {
    id: "bg-download",
    path: "examples/bg-download",
    hostBundleId: "com.expotargets.example.bg-download",
    androidPackage: "com.expotargets.example.bgdownload",
    hostDisplayName: "ET BgDL",
    extensionName: "ET BgDL Target",
    extensionAliases: ["ET BgDL Target", "bg-download"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "location-push": {
    id: "location-push",
    path: "examples/location-push",
    hostBundleId: "com.expotargets.example.location-push",
    hostDisplayName: "ET location-push",
    extensionName: "ET location-push",
    extensionAliases: ["location-push"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  matter: {
    id: "matter",
    path: "examples/matter",
    hostBundleId: "com.expotargets.example.matter",
    hostDisplayName: "ET Matter",
    extensionName: "ET Matter Target",
    extensionAliases: ["ET Matter Target", "matter"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "classkit-context": {
    id: "classkit-context",
    path: "examples/classkit-context",
    hostBundleId: "com.expotargets.example.classkit-context",
    hostDisplayName: "ET ClassKit",
    extensionName: "ET ClassKit Target",
    extensionAliases: ["ET ClassKit Target", "classkit-context"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "print-service": {
    id: "print-service",
    path: "examples/print-service",
    hostBundleId: "com.expotargets.example.print-service",
    androidPackage: "com.expotargets.example.printservice",
    hostDisplayName: "ET Print",
    extensionName: "ET Print Target",
    extensionAliases: ["ET Print Target", "print-service"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "smart-card": {
    id: "smart-card",
    path: "examples/smart-card",
    hostBundleId: "com.expotargets.example.smart-card",
    hostDisplayName: "ET SmartCard",
    extensionName: "ET SmartCard Target",
    extensionAliases: ["ET SmartCard Target", "smart-card"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "virtual-conference": {
    id: "virtual-conference",
    path: "examples/virtual-conference",
    hostBundleId: "com.expotargets.example.virtual-conference",
    hostDisplayName: "ET VirtConf",
    extensionName: "ET VirtConf Target",
    extensionAliases: ["ET VirtConf Target", "virtual-conference"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  watch: {
    id: "watch",
    path: "examples/watch",
    hostBundleId: "com.expotargets.example.watch",
    hostDisplayName: "ET watch",
    extensionName: "ET watch",
    extensionAliases: ["watch"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
  "watch-widget": {
    id: "watch-widget",
    path: "examples/watch-widget",
    hostBundleId: "com.expotargets.example.watch-widget",
    androidPackage: "com.expotargets.example.watchwidget",
    hostDisplayName: "ET watch-widget",
    extensionName: "ET watch-widget",
    extensionAliases: ["watch-widget"],
    payloadMarker: "ready",
    completeButton: "",
    testIds: {
      screenRoot: "screen-root",
      clearPayload: "btn-clear-payload",
      lastPayload: "text-last-payload",
    },
  },
};

/** Launch id for Devicewright — Android may diverge when iOS IDs contain hyphens. */
export function hostLaunchId(
  entry: TargetCatalogEntry,
  platform: "ios" | "android",
): string {
  if (platform === "android" && entry.androidPackage) {
    return entry.androidPackage;
  }
  return entry.hostBundleId;
}

/** System Share Sheet rows we must never tap (mirrors ShareSheetSmoke). */
export const BLOCKED_SHEET_LABELS = new Set([
  "Create Watch Face",
  "Watch Face",
  "Print",
  "Copy",
  "Save Image",
  "Save to Files",
  "Assign to Contact",
  "Add to Shared Album",
  "Edit Actions",
  // Note: View More / More are expanded intentionally via point-probe — not blocked there.
  "Apps",
  "Close",
  "Cancel",
]);
