import { type SpawnSyncReturns, spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import process from 'node:process';

export type HermesExportRunner = (
  command: string,
  args: string[],
  opts: { cwd: string; env: NodeJS.ProcessEnv; stdio: 'inherit' | 'pipe' }
) => SpawnSyncReturns<Buffer | string>;

export type HermesExportOptions = {
  projectRoot: string;
  /** Project-root relative or absolute entry (targets/.../index.tsx). */
  entryFile: string;
  /** Absolute path for main.jsbundle (Hermes bytecode when bytecode=true). */
  bundleOutput: string;
  /** Optional assets dest for images referenced by the entry. */
  assetsDest?: string;
  bytecode?: boolean;
  platform?: 'ios' | 'android';
  /** Injectable for tests. */
  run?: HermesExportRunner;
};

/**
 * Bundle a RN extension entry with Expo `export:embed` (Hermes bytecode by default).
 * Same engine path Xcode uses for Release embed, suitable for App Group sideload.
 */
export function exportTargetHermesBundle(
  options: HermesExportOptions
): { bundleOutput: string } {
  const {
    projectRoot,
    entryFile,
    bundleOutput,
    assetsDest,
    bytecode = true,
    platform = 'ios',
  } = options;
  const run = options.run ?? spawnSync;

  fs.mkdirSync(path.dirname(bundleOutput), { recursive: true });
  if (assetsDest) {
    fs.mkdirSync(assetsDest, { recursive: true });
  }

  const entryPath = path.isAbsolute(entryFile)
    ? entryFile
    : path.resolve(projectRoot, entryFile);

  if (!fs.existsSync(entryPath)) {
    throw new Error(`Extension entry not found: ${entryPath}`);
  }

  const args = [
    'expo',
    'export:embed',
    '--platform',
    platform,
    '--entry-file',
    entryPath,
    '--bundle-output',
    bundleOutput,
    '--dev',
    'false',
    '--minify',
    'true',
  ];
  if (bytecode) {
    args.push('--bytecode');
    args.push('--unstable-transform-profile', 'hermes');
  }
  if (assetsDest) {
    args.push('--assets-dest', assetsDest);
  }

  const result = run('npx', args, {
    cwd: projectRoot,
    env: process.env,
    stdio: 'inherit',
  });

  if (result.status !== 0) {
    throw new Error(
      `expo export:embed failed for ${entryFile} (exit ${result.status ?? 'null'})`
    );
  }
  if (!fs.existsSync(bundleOutput)) {
    throw new Error(
      `expo export:embed succeeded but missing bundle at ${bundleOutput}`
    );
  }
  return { bundleOutput };
}

/** Write a Metro-requireable map for host Asset.fromModule resolution. */
export function writeExtensionBundleAssetModules(opts: {
  assetsRoot: string;
  targetNames: string[];
}): string {
  const { assetsRoot, targetNames } = opts;
  fs.mkdirSync(assetsRoot, { recursive: true });
  const lines = [
    '// GENERATED by `npx expo-targets export-extension-bundles` — do not edit.',
    'module.exports = {',
    ...targetNames.map(
      (name) =>
        `  ${JSON.stringify(name)}: require(${JSON.stringify(`./bundles/${name}/main.jsbundle`)}),`
    ),
    '};',
    '',
  ];
  const outPath = path.join(assetsRoot, 'extensionBundleModules.js');
  fs.writeFileSync(outPath, lines.join('\n'));
  return outPath;
}
